### ISSUE TITLE
Failing example in readme.md

### ISSUE THREAD

**Issue by cristianvasquez** [itemsapi/itemsjs#102]
Hi, 

I'm testing the library using the example of README.md, 

but it fails: 

```
At:   node_modules/fastbitset/FastBitSet.js:488

const count = Math.max(this.words.length, otherbitmap.words.length);
TypeError: Cannot read properties of undefined (reading 'words')
```

**Comment by cigolpl** [comment]
Hey @cristianvasquez, thanks for info. It's fixed now

**Comment by carolineboeykens** [comment]
@cigolpl, Do you know what was wrong here? We are getting the same error so maybe there is something wrong with our data but I can't figure out what went wrong.

**Comment by cigolpl** [comment]
@carolineboeykens, in that case:

```js
const movies = itemsjs.search({
  per_page: 1,
  sort: 'name_asc',
  // full text search
  // query: 'forrest gump',
  filters: {
    tags: ['1980s']
  }
})
```
the tag: "1980s" was not present in a JSON. 

Itemsjs should handle it and i.e. throw Error with "The filter value does not exist" so it would be clear
