### ISSUE TITLE
Transpile code to ES5 before publishing to NPM

### ISSUE THREAD

**Issue by saminzadeh** [itemsapi/itemsjs#12]
First off, thanks for developing this lib. It's really nice.

I am running into a minification issue because the code published to NPM isn't transpiled to ES5 (I noticed there are some `=>` functions in the dist). This is causing issues when trying to build it with[ create-react-app](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify). 

I'll be glad to submit a PR for this

**Comment by cigolpl** [comment]
@saminzadeh I am happy you like it. If you submit a PR for this it will be a big help
