### ISSUE TITLE
Need for several search comparaison operators

### ISSUE THREAD

**Issue by Bartaf83** [itemsapi/itemsjs#121]
There's nothing apparently related to any search comparison settings in the documentation
Or a way to provide the search logic to itemjs engine
Can such as features be available in next new versions ?

**Comment by cigolpl** [comment]
Do you mean relevancy algorithms ? ItemsJS can integrate with any JS fulltext search so you can configure results orders as much as you want

**Comment by Bartaf83** [comment]
Nope, it's not about relevancy algorithms. I mean stuff like that the comparaison would use an "include" instead of the standard equality between strings, a "Starts With" or other operators that we can see for example [in this module's feature options](https://www.ag-grid.com/archive/25.0.0/documentation/javascript/filter-provided-simple/#simple-filter-options) when making the search

**Comment by cigolpl** [comment]
Could you provide an example i.e. input, your expected output and some description ? 

If you need filters options you can just use:

```js
var result = itemsjs.search({
  query: 'shoes',
  filter: function(item) {
    return item.rating >= 8 && item.reviews_count >= 200;
  }
});
```

**Comment by Bartaf83** [comment]
Well, thanks , it's kinda what i've been looking for.

So i've been trying with the filter function , at first i made [this first stackblitz](https://react-ts-ahc76u.stackblitz.io) in which I pass the data and the config and then I make the filtering and I'm getting two items as result in the console: 
![image](https://user-images.githubusercontent.com/12170979/204855053-f9aec43f-65e3-4fb4-bee5-9be92fffb782.png)

But then I forked that same demo and I just inverted the boolean returned by the filter function (line 108 in the code)
and I expected I would get the opposite result (which means the reverse items of what i got in the first demo)
but i got an empty array as items in the searchResult
![image](https://user-images.githubusercontent.com/12170979/204856567-4d83c47b-3e6f-4f44-a7ca-7aef5e69aebe.png)

By doing that I'm trying to apply the NOT operator to the result I got at first but it's not working
Can you please help me to make it work ?
