### ISSUE TITLE
[Feature Request] A 'better than' filter logic on tags.

### ISSUE THREAD

**Issue by Kugeleis** [itemsapi/itemsjs#124]
Imagine you have a list of properties where it ranks from poor to great like
```
USB 1.1
USB 2.0
USB 3.0
USB 3.1
```
If I select `USB 2.0` it should include 3.0 and 3.1, too. So e.g. the alphabetic order is like a ranking and the filter should include the selected and "better".

**Comment by SergeyRe** [comment]
In your case you have to intoduce new field: say "min requirements" and the calculate values for any items as following: (it will be multiple in general)
USB 1.0 and better for all
USB 2.0  and better for all except USB 1.0
etc.
