### ISSUE TITLE
Fuzzy search / prefix match?

### ISSUE THREAD

**Issue by 684efs3** [itemsapi/itemsjs#131]
Is there a way to enable fuzzy search or prefix match? I am using MiniSearch, but filter doesn't work with native search turned off. I am trying to filter a range of values. I think it's possible for me to implement this with MiniSearch, but then I thought maybe I don't need MiniSearch. I am using MiniSearch for fuzzy and prefix matching. With ItemsJS, sometimes if I enter the first two letters of a search item, the results will be blank, but then as I type out more letters, the results will show up.

**Comment by cigolpl** [comment]
ItemsJS by itself doesn't come with built-in functionality for fuzzy search or prefix match. However, it's designed to be highly flexible and can easily integrate with search engines like MiniSearch, Lunr, and other JavaScript search libraries.

For more detailed steps on how to integrate with either Lunr or MiniSearch, I'd recommend checking out the following guides in our documentation:

[Lunr integration guide](https://github.com/itemsapi/itemsjs/blob/master/docs/lunr2-integration.md)
[MiniSearch integration guide](https://github.com/itemsapi/itemsjs/blob/master/docs/minisearch-integration.md)

**Comment by cigolpl** [comment]
ItemsJS by default relies on Lunr version 1, which doesn't have built-in functionality for fuzzy search or prefix match. It's worth noting that the newer Lunr version 2 introduced these functionalities. For more details on searching capabilities with Lunr version 2, you can refer to the official Lunr documentation here: [Lunr Searching Guide](https://lunrjs.com/guides/searching.html).

That said, while ItemsJS doesn't natively support these advanced search features, it is designed to be highly adaptable. You can integrate it with other search engines like MiniSearch and even with Lunr version 2.

For steps on how to achieve integration with MiniSearch or Lunr version 2, please check out the following guides in our documentation:

[Lunr v2 integration guide](https://github.com/itemsapi/itemsjs/blob/master/docs/lunr2-integration.md)
[MiniSearch integration guide](https://github.com/itemsapi/itemsjs/blob/master/docs/minisearch-integration.md)

**Comment by 684efs3** [comment]
That's really helpful! And thank you very much for creating this library and keeping it updated.

Are there any plans to update ItemsJS to Lunr 2?

**Comment by cigolpl** [comment]
Thank you for your feedback! It's appreciated. While it would be great to have built-in Lunr 2 support in ItemsJS, plans for its integration are still undetermined. Currently, the "filter" feature in ItemsJS doesn't work when native search is disabled. We hope for future updates to expand its capabilities.

**Comment by leeoniya** [comment]
shameless plug for https://github.com/leeoniya/uFuzzy :)

i've done a pretty extensive comparison and live demos of a few dozen search libs here: https://github.com/leeoniya/uFuzzy#a-biased-appraisal-of-similar-work
