### ISSUE TITLE
window.itemsjs not a function

### ISSUE THREAD

**Issue by ssanch** [itemsapi/itemsjs#15]
It seems like the last commit broke the library. I am getting this error when attempting to initialize it (Using it client side). I thought the last change was supposed to provide ES5 compatibility.

Ideas?

**Comment by cigolpl** [comment]
@ssanch thanks for information! Please try to use below script which is almost latest version:
`<script src="https://unpkg.com/itemsjs@1.0.39/dist/itemsjs.min.js"></script>`

Once we fix it I hope it will work like always and you could use latest version

**Comment by saminzadeh** [comment]
@ssanch How are you including the bundle? Do you have an example?

This is an example of it working with latest master:
https://codesandbox.io/s/0ojmnxxokp

**Comment by ssanch** [comment]
Hey, it seems like you guys are actively working on this, thank you!

I did nothing special really, I just imported the bundle using a `script` tag in my html. For now I am using the previous stable version and that works just fine. Feel free to close this issue as it's the same issue opened by @cigolpl
