### ISSUE TITLE
for general understanding -index life cycle

### ISSUE THREAD

**Issue by SergeyRe** [itemsapi/itemsjs#32]
is it right that idea to  generate search index  every user session?
so we don't keep it precalculated and ready to use   in static form?

**Comment by cigolpl** [comment]
@SergeyRe if you make this precalculation once i.e. in SPA application (i.e. with Vue, React or Angular) or on the backend side then it will be faster. If you don't have so much data i.e. there is less than 1000 items there should not be so much difference in terms of performance.

**Comment by SergeyRe** [comment]
i think this is a very promising project and perfomance as fn (data size, number and types of facets) is thing for more deep investigation . I see at least 3 ways for expanding "1000 limit" 
1.Option to exlude full-text search ( sometimes it is not required feature)
2.Index precalculation
3.Dividing data to smaller parts (with one facet value fixed )

**Comment by cigolpl** [comment]
@SergeyRe thanks!

Ad. 1) Good idea
Ad. 2) Good idea but might be challenging
Ad. 3) Not exactly sure what you mean. Maybe caching facets results for first rendering ?

**Comment by SergeyRe** [comment]
as for p.3 -it is maybe general common sense idea -non specific to your search component
If you have data , and searching in fact doing at few different parts  -do not combine  all data  at one massive -make few subsets of data , at least for perfomace reasons. i.e. if your data has user country facet and country of user have to be determed at the beginning of session -better to make special subset of data for every possible country ( not sure -but hope it is clear )
by the way -i know at least one ancient forerunner of your project
https://github.com/eikes/facetedsearch
i made demo implementation of it here
http://roonready.com/ (code is not obfuscated)

**Comment by SergeyRe** [comment]
the best thing in ItemsJs is that it is live and developing 👍
