### ISSUE TITLE
Help with pagination needed

### ISSUE THREAD

**Issue by bellerophons-pegasus** [itemsapi/itemsjs#34]
Hi @cigolpl,

you have created an awesome library!

I am trying to adapt it for a bibliography list and currently am stuck at how to paginate through the items. While looking around I also noticed that the example you provided on [jsfiddle](https://jsfiddle.net/cigol/0ef9qeos/5/) does not provide pagination. There a 100 search results are mentioned, but only the first 12 items can be seen. 

What am I missing?

**Comment by cigolpl** [comment]
Hey @bellerophons-pegasus thanks! This demo is quite limited. It's lacking i.e. pagination.
I was using in other Vue.js & ItemsJS projects something like this to make pagination:

```html
<div class="pagination-bar text-center">
  <paginate
     :page-count="Math.ceil(searchResult.pagination.total / searchResult.pagination.per_page)"
     :click-handler="goToPage"
     :prev-text="'Prev'"
     :next-text="'Next'"
     :container-class="'pagination'">
  </paginate>
</div>
```  

and also `Vue.component('paginate', VuejsPaginate)`

When I have more time I'll try to update this demo. So far good luck with bibliography list

**Comment by cigolpl** [comment]
I see you can find some codebase for pagination and breadcrumbs here:

- https://github.com/itemsapi/curlist/blob/itemsjs-elasticsearch/views/catalog.html.twig
- https://github.com/itemsapi/curlist/blob/itemsjs-elasticsearch/assets/custom.js

**Comment by bellerophons-pegasus** [comment]
Thank you! I'll fiddle around a bit and will let you know, when I managed it.

**Comment by bellerophons-pegasus** [comment]
Hi again,

I've finally managed it an can now page through my [bibliography page](https://bellerophons-pegasus.github.io/lobib/testItemsJS/index.html)! 
I forked your example on jsfiddle and [expanded](https://jsfiddle.net/3ybkqa05/2/) it. Thanks again.

**Comment by cigolpl** [comment]
Looks good! I've added your jsfiddle example to demo page (https://github.com/itemsapi/itemsjs/edit/master/docs/demo.md)
