### ISSUE TITLE
Dependency on lodash-cli does not seem almost dependency free

### ISSUE THREAD

**Issue by benjaminisi** [itemsapi/itemsjs#35]
This library does what I need.  I'm put off by the dependencies pulled in by lodash-cli that appears as both a dependency and a dev-dependency in package.json.

**Comment by cigolpl** [comment]
Good point. `lodash-cli` seems to be put there unintentionally. It doesn't make sense for it to be there. Feel free to make PR or I'll  just fix it in a few days

**Comment by cigolpl** [comment]
Fixed https://github.com/itemsapi/itemsjs/commit/e943bf50eef7aac9b2d3dc673eee8d38d13bdd7f and published new version to npmjs registry
