### ISSUE TITLE
Allow "like" search query

### ISSUE THREAD

**Issue by regisphilibert** [itemsapi/itemsjs#37]
Currently using this list of items:

- V1001
- P1001
- 1001
- Basic
and entering `100` in the search field, only `1001` will be returned.
When entering `asic, __Basic__ wil not be returned.

I have looked #28 but could not find the proper "token" for what I am looking for.

I wonder if there is a configuration setting allowing the like searchers.
I've tried wrapping the query value between `*` à la Lurnr.js but I think those are escaped by ItemsJS.

Thanks.

**Comment by cigolpl** [comment]
The idea seems useful. Is the like feature '*' supported by lunr.js ?

**Comment by regisphilibert** [comment]
There is a notion of `wildcards` if this can help: https://lunrjs.com/guides/searching.html

**Comment by cigolpl** [comment]
Thanks. We'll need to upgrade Lunr.js from 1.0 to the newest 2.x soon. Fortunately API seems almost the same https://lunrjs.com/guides/upgrading.html so upgrading should not be a problem.

Additional features will be available by default then i.e. wildcard, boosting or searching by field

One change which I see will be:

> The behaviour of the search has changed slightly, multi-term searches are now combined with OR, where they used to be combined with AND.
> 
> Practically this change means that a given search will return more documents in 2.x than it did previously, with the most relevant results returned first.

Not sure yet if this change will be good or not

**Comment by cigolpl** [comment]
@regisphilibert you can use Lunr 2.x (or plenty of others) by custom integration. Example is here https://github.com/itemsapi/itemsjs/blob/master/docs/lunr2-integration.md. Thanks to that you have full control over search features (wildcards, etc)
