### ISSUE TITLE
How to prefilter search, when passing paramenter from URL

### ISSUE THREAD

**Issue by acerosillo** [itemsapi/itemsjs#38]
Hi guys,

I have a URL that is passing some parameters (strings), that I want the search page to have filtered when you land on the page : 

v-careers-search-page.html?careerssearch=xxx&Job_family_group=xxx&Organisation_name=xxx&Primary_location_country=GB

so for example when I land on the search page, I would like the 'Primary_location_country' checkbox to prefilter all GB countries, but also be able to filter any other options given from GB

hope this makes sense..

cheers,
A

**Comment by cigolpl** [comment]
Hi, this is more js question. Such a lib https://medialize.github.io/URI.js/ may help you with parsing url parameters (if you are doing it on the frontend side)

**Comment by acerosillo** [comment]
I have this : 

            computed: {
                searchResult: function () {
                    var result = itemsjs.search({
                        query: this.query,
                        //filters: this.filters

                         filter: function(i) {
                             return i.Primary_Location_Country == 'GB';
                         }


                         prefilter: function(items) {
                             return items.filter(item => {
                                 return item.Primary_Location_Country == "US";
                             })
                         } 
                    })
                    return result
                }
            }

this works, but when I start click the other aggregated checkboxs they don't seem to re-filter.

**Comment by cigolpl** [comment]
I am closing because this is more Vue.js related question
