### ISSUE TITLE
Faceted search with OR

### ISSUE THREAD

**Issue by lbineau** [itemsapi/itemsjs#4]
Hi @cigolpl,
Thank you for your library, it is really nice, I have been looking for a while for a proper faceted search lib without jQuery.

I have a question about the faceted search.
```javascript
var movies = itemsjs.search({
  per_page: 1,
  sort: 'name_asc',
  filters: {
    tags: ['1980s', '1990s']
  }
})
```
Will return all movies with 1980s AND 1990s tags.
Is it possible to search with OR operator? If I want all movies with 1980s OR 1990s.

Thanks a lot.

**Comment by cigolpl** [comment]
Hello @lbineau, thanks for feedback!

Yes, it's possible to use OR. You need to set `conjunction` to false in `tags` configuration like:

```js 
aggregations: {
    tags: {
      title: 'Tags',
      conjunction: false, 
      size: 10
}
```

**Comment by lbineau** [comment]
Thanks, it works like a charm!
