### ISSUE TITLE
Overriding the 1000 item limit

### ISSUE THREAD

**Issue by jibinycricket** [itemsapi/itemsjs#44]
According to the project description, there's a 1000 element limit. Is there anyway to override this? I haven't run into that limit yet, but I'd like to get ahead of it in case I do.

`Full text, faceted, dependency free search engine in javascript. Created to perform fast search on small json dataset (up to 1000 elements).`

**Comment by cigolpl** [comment]
In version 2.0 it can work now with 100K items. Of course such a dataset is better on the backend side as you can index it once at the runtime. On the browser side every user needs to wait for indexing but I'd say for that case 10K elements should be ok (depends on JSON file size)
