### ISSUE TITLE
json from fetch api is not working

### ISSUE THREAD

**Issue by Kugeleis** [itemsapi/itemsjs#58]
While the example uses a js file with a variable in it I try to fetch data and return it a json. itemsjs does not recognize the array. Providing the identical data as js like in the example works fine. 
![fetch-vs-var](https://user-images.githubusercontent.com/9948777/109303625-5d616680-783b-11eb-84db-3671315054c0.png)

**Comment by cigolpl** [comment]
It is more a problem of how you handle data after making request and not ItemsJS itself. 

Let's try to stringify and parse an array and it's gonna work:

```js
var data = JSON.parse(JSON.stringify(obj));
```
