### ISSUE TITLE
Updating to v2 results in doc count of 1

### ISSUE THREAD

**Issue by domoritz** [itemsapi/itemsjs#69]
I am trying to switch to v2 but in https://github.com/domoritz/domoritz.github.io/blob/b47cdbed49dfcd4df2fb8459c8669b78909b2744/_includes/pubfilter.js#L154, the aggregations on a search result always have doc count 1.
 
<img width="1256" alt="Screen Shot 2021-03-31 at 22 18 17" src="https://user-images.githubusercontent.com/589034/113247028-ffc39e00-926e-11eb-8819-379cbabb9e9e.png">

Did I miss a step when updating to v2?

**Comment by cigolpl** [comment]
Everything should work out of the box with upgrading to v2.0. It's compatible with v1.0. 

There was a bug when you provide you own non integer "id" but now it is fixed

**Comment by domoritz** [comment]
Thank you for the quick fix. The new version looks great. It's fast and I can enable full text search.
