### ISSUE TITLE
Unnecessary override of the title property in the buckets creation

### ISSUE THREAD

**Issue by vanch3d** [itemsapi/itemsjs#78]
The configuration for an aggregation defines a `title` property, such as: 

```js
{
  aggregations: {
    tags: {
      title: 'Tags',
      // conjunctive facet (AND)
      conjunction: true,
      // the default is 10
      size: 20
    },
    rating: {
      title: 'Actors',
      // non conjunctive facet (OR)
      conjunction: false,
      // it is sorting by value (not by count). 'count' is the default
      sort: 'term',
      order: 'asc',
      size: 5
    }
  }
}
```

I assumed it could be used for the UI part of the facets, once the search has been succesful.
But the code for creating the buckets automatically generates a `title` property out of a humanised version of the id, see

https://github.com/itemsapi/itemsjs/blob/06e2e70812294e94b3759bf7fda47db4633ac765/src/helpers.js#L236-L241

- Is `title` used anywhere else in the code or by other integrations? 
- Would it make sense to use the humanised version *only* is the `title` has *not* been defined in the configuration, e.g.

```js
return {      
    name: k,      
    title: aggregations[k].title || humanize(k),      
    position: position++,      
    buckets: buckets    
};



```

**Comment by cigolpl** [comment]
Hey @vanch3d, thanks for catching it. The `title` is not used anywhere else. Feel free to create a PR
