### ISSUE TITLE
[Chore] tags and release

### ISSUE THREAD

**Issue by noraj** [itemsapi/itemsjs#89]
There are [git tags](https://github.com/itemsapi/itemsjs/tags) only up to v1.0.30. So version between 1.0.31 (4 years ago) to 1.0.49
 (2 years ago) and also the whole 2.x.x (2.0.0 to 2.1.10) are released on [npmjs](https://www.npmjs.com/package/itemsjs) but have no git tag.

**Comment by cigolpl** [comment]
Agree. Please propose next time some solution so it will proceed faster - adding a tag is repetitive job so maybe there is a tool which do it out of the box like https://github.com/pantheon-systems/autotag

**Comment by noraj** [comment]
Ok, I'm personally pushing tags manually and have added the step in the doc of my projects to avoid forgetting eg. https://noraj.github.io/haiti/#/pages/publishing.
Basically adding a tag is the last step you do before pushing the release. But yeah since you have a lot missing in your history maybe an automated tool could help fix that.

**Comment by cigolpl** [comment]
I've started using releases from now. I'll try to also update the historical releases step by step.
Thanks for your feedback! I am closing now.
